### ISSUE TITLE
Windows version

### ISSUE THREAD

**Issue by 0xNacho** [RobeDM/LIBIRWLS#2]
Do you have in mind to release a Windows version?

**Comment by RobeDM** [comment]
Hi,

We are currently working on it. It is not easy to compile C code designed for Unix like operating systems.

**Comment by 0xNacho** [comment]
Nice! 
I'm willing to try it. Thanks!

**Comment by RobeDM** [comment]
We have included precompiled versions for windows of 32 and 64 bits and demo scripts for them.
